const filterParam = {
  filter: {
    id: "1",
    isDefault: true,
    friendlyName: "Morning Gap Ups",
    currentPriceMin: 0,
    currentPriceMax: 300,
    percentChangeMin: -50,
    percentChangeMax: 50,
    intradayPercentChangeMin: -50,
    intradayPercentChangeMax: 50,
    percentChange1MinMin: -10,
    percentChange1MinMax: 10,
    percentChange5MinMin: -20,
    percentChange5MinMax: 20,
    floatRotationsMin: 0,
    floatRotationsMax: 100,
    volumeMin: 0,
    volumeMax: 100000000,
    volume1MinMin: 0,
    volume1MinMax: 1000000,
    volume5MinMin: 0,
    volume5MinMax: 1000000,
    capitalMin: 0,
    capitalMax: 500000000,
    capital1MinMin: 0,
    capital1MinMax: 20000000,
    capital5MinMin: 0,
    capital5MinMax: 50000000,
    marketCapMin: 0,
    marketCapMax: 100000,
    floatMin: 0,
    floatMax: 500,
    rVolMin: 0,
    rVolMax: 10,
    rVolChangeMin: -100,
    rVolChangeMax: 500,
    volatilityMin: 0,
    volatilityMax: 300,
    atrMin: 0,
    atrMax: 5,
    rangeMin: 0,
    rangeMax: 100,
    fiftyTwoWeekRangeMin: 0,
    fiftyTwoWeekRangeMax: 100,
    spreadMin: 0,
    spreadMax: 1,
    bidSizeMin: 0,
    bidSizeMax: 100000,
    askSizeMin: 0,
    askSizeMax: 100000,
    percentFromVwapMin: -10,
    percentFromVwapMax: 10,
    latestVwapCross: 30,
    percentOfAverageOneMinVolumeMin: 0,
    percentOfAverageOneMinVolumeMax: 200,
    volumeTrend: "Any",
    latestLod: 30,
    latestHod: 30,
    isGapping: "Either",
    isHalted: "Either",
    orderBy: "volumeDesc",
    columns: [
      "name",
      "currentPrice",
      "percentChange",
      "oneMinuteVolume",
      "fiveMinuteVolume",
      "totalVolume",
      "totalCapital",
      "float",
      "rVol",
      "volatility",
    ],
    $$hashKey: "object:12",
  },
};

export { filterParam };
